Customer
--------
Orders = [items{vendor}] {address} {user} {payment} {delivery} {amount}
Bestsellers group by date


Chef
----
Chef('items.vendor.id'==userId){
  user
  address
}


Delivery Boy
------------
Group by vendor count(items) sum(item.price)

(Vendor:id){
  items
}

Group by order status